import i18n from 'i18next'
import {initReactI18next} from 'react-i18next'
const resources={
 en:{translation:{title:'iRacing Analyst',sessions:'Sessions',import:'Import telemetry',waiting:'Waiting for iRacing',recording:'Recording',best:'Best lap',median:'Median pace',optimal:'Sector optimal',potential:'Potential gap',corners:'Segments',recommendations:'Next session',noSession:'Import an IBT/NPZ file or complete an iRacing session.',selected:'Best',reference:'Median',confidence:'Confidence',sourceLap:'Source lap',loss:'Available gain',speed:'Speed',throttle:'Throttle',brake:'Brake',steering:'Steering',delta:'Delta','rec.inconsistent.title':'Build consistency','rec.inconsistent.message':'Repeat the reference inputs before pushing the entry. This segment has the largest spread.','rec.lateThrottle.title':'Reach full throttle earlier','rec.lateThrottle.message':'The throttle ramp is long after the apex. Prioritize rotation before acceleration.','rec.lowSpeed.title':'Protect minimum speed','rec.lowSpeed.message':'Avoid over-slowing the car; use the source lap as the entry reference.','rec.corrections.title':'Reduce steering corrections','rec.corrections.message':'Unwind the steering progressively and delay throttle if the car is not settled.','rec.segment.title':'Focus on this segment','rec.segment.message':'Reproduce the source lap inputs; this is the largest confirmed time opportunity.'}},
 ru:{translation:{title:'iRacing Аналитик',sessions:'Сессии',import:'Импорт телеметрии',waiting:'Ожидание iRacing',recording:'Идёт запись',best:'Лучший круг',median:'Медианный темп',optimal:'Sector Optimal',potential:'Потенциал',corners:'Сегменты',recommendations:'Следующая сессия',noSession:'Импортируйте IBT/NPZ или завершите сессию iRacing.',selected:'Лучший',reference:'Медианный',confidence:'Уверенность',sourceLap:'Круг-источник',loss:'Доступный выигрыш',speed:'Скорость',throttle:'Газ',brake:'Тормоз',steering:'Руль',delta:'Дельта','rec.inconsistent.title':'Закрепи повторяемость','rec.inconsistent.message':'Сначала повтори действия референса, не переатаковывая вход: здесь самый большой разброс.','rec.lateThrottle.title':'Раньше выходи на полный газ','rec.lateThrottle.message':'После апекса газ набирается долго. Сосредоточься на повороте машины до разгона.','rec.lowSpeed.title':'Сохрани минимальную скорость','rec.lowSpeed.message':'Не замедляй машину лишний раз; используй круг-источник как ориентир входа.','rec.corrections.title':'Уменьши коррекции рулём','rec.corrections.message':'Плавно распускай руль и не добавляй газ, пока машина не стабилизирована.','rec.segment.title':'Сосредоточься на сегменте','rec.segment.message':'Повтори действия круга-источника: здесь подтверждена крупнейшая потеря времени.'}}
}
i18n.use(initReactI18next).init({resources,lng:localStorage.getItem('language')||'ru',fallbackLng:'en',interpolation:{escapeValue:false}})
export default i18n

