import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{useTranslation}from'react-i18next'
import{Line,LineChart,ReferenceDot,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts'
import'./i18n'
import'./styles.css'
import type{Insight,Report,Series,Session,TrackMap as TrackMapType}from'./types'

const fmt=(v:number|null)=>v==null?'—':`${Math.floor(v/60)}:${(v%60).toFixed(3).padStart(6,'0')}`
async function json<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);if(!r.ok)throw new Error(await r.text());return r.status===204?undefined as T:r.json()}

function App(){
 const{t,i18n}=useTranslation();const[sessions,setSessions]=useState<Session[]>([]);const[report,setReport]=useState<Report|null>(null);const[series,setSeries]=useState<Series|null>(null);const[health,setHealth]=useState({simulator_connected:false,recording:false});const[busy,setBusy]=useState(false);const[error,setError]=useState('')
 const reload=()=>json<Session[]>('/api/sessions').then(setSessions)
 useEffect(()=>{reload();const timer=setInterval(()=>{json<typeof health>('/api/health').then(setHealth);reload()},3000);return()=>clearInterval(timer)},[])
 const open=async(id:string)=>{const next=await json<Report>(`/api/sessions/${id}`);setReport(next);setSeries(null);if(next.best_lap&&next.median_lap)setSeries(await json<Series>(`/api/sessions/${id}/telemetry?selected_lap=${next.best_lap}&reference_lap=${next.median_lap}`))}
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');const body=new FormData();body.append('file',file);try{const r=await json<Report>('/api/import',{method:'POST',body});await reload();await open(r.session_id)}catch(x){setError(String(x))}finally{setBusy(false);e.target.value=''}}
 const remove=async()=>{if(!report||!confirm(t('delete')+'?'))return;await json(`/api/sessions/${report.session_id}`,{method:'DELETE'});setReport(null);setSeries(null);reload()}
 const clear=async()=>{if(!confirm(t('confirmClear')))return;await json('/api/sessions?confirm=true',{method:'DELETE'});setReport(null);setSeries(null);reload()}
 const chart=useMemo(()=>series?.distance_pct.map((x,i)=>({x:x*100,speed:(series.selected.speed[i]||0)*3.6,refSpeed:(series.reference.speed[i]||0)*3.6,throttle:(series.selected.throttle[i]||0)*100,refThrottle:(series.reference.throttle[i]||0)*100,brake:(series.selected.brake[i]||0)*100,refBrake:(series.reference.brake[i]||0)*100,steering:series.selected.steering[i]||0,refSteering:series.reference.steering[i]||0,delta:series.selected.delta[i]||0,refDelta:0})),[series])
 const language=i18n.language.startsWith('ru')?'ru':'en';const swap=()=>{const next=language==='ru'?'en':'ru';localStorage.setItem('language',next);i18n.changeLanguage(next)}
 const segmentName=(name:string)=>name.startsWith('Zone ')?`${t('zone')} ${name.slice(5)}`:name
 return <div className="app"><header><div><span className="mark">IA</span><h1>{t('title')}</h1></div><div className="status"><span className={health.recording?'dot live':'dot'}/>{health.recording?t('recording'):t('waiting')}<button onClick={swap}>{language.toUpperCase()}</button></div></header>
 <div className="layout"><aside><h2>{t('sessions')}</h2><label className="upload">{busy?'…':t('import')}<input type="file" accept=".ibt,.npz" onChange={upload}/></label>{error&&<p className="error">{error}</p>}<div className="sessionList">{sessions.map(s=><button key={s.id} className={report?.session_id===s.id?'active':''} onClick={()=>open(s.id)}><strong>{s.track}</strong><span>{s.session_type}{s.layout?` · ${s.layout}`:''}</span><small>{s.valid_laps} {t('validLaps')} · {fmt(s.best_time)}</small></button>)}</div>{sessions.length>0&&<button className="clearButton" onClick={clear}>{t('clear')}</button>}</aside>
 <main>{!report?<div className="empty"><div className="track">⌁</div><p>{t('noSession')}</p></div>:<><section className="hero"><div><p className="eyebrow">{report.session_type} · {report.car}</p><h2>{report.track}</h2><span>{report.layout||'Road'} · {report.official_turns??'—'} {t('turns')} · {report.data_sufficiency.valid_laps} {t('validLaps')}</span><p className={`sufficiency ${report.data_sufficiency.status}`}>{t(report.data_sufficiency.message_key)}</p></div><div className="cards"><Metric label={t('best')} value={fmt(report.best_time)}/><Metric label={t('median')} value={fmt(report.median_time)}/><Metric label={t('optimal')} value={fmt(report.sector_optimal)}/><Metric accent label={t('potential')} value={report.potential_gap==null?'—':`-${report.potential_gap.toFixed(3)}s`}/></div></section>
 <section className="panel mapPanel"><h3>{t('map')}</h3><TrackMapView map={report.track_map}/>{!report.track_map.available&&<p className="muted">{t('trajectoryMissing')}</p>}</section>
 <InsightPanel title={t('whyFaster')} insights={report.strengths} empty={t('noInsights')}/>
 <section className="panel"><div className="panelTitle"><h3>{t('corners')}</h3><button className="danger" onClick={remove}>{t('delete')}</button></div><div className="segments">{report.segments.map(s=><article key={s.id}><div><b>{segmentName(s.name)}</b><span className="gain">{s.delta_to_best>0?`-${s.delta_to_best.toFixed(3)}s`:'—'}</span></div><div className="bar"><i style={{width:`${Math.min(100,Math.max(5,s.delta_to_best*350))}%`}}/></div><small>{t('sourceLap')} {s.source_lap} · {Math.round(s.minimum_speed_kph)} km/h min</small></article>)}</div></section>
 {chart&&<section className="panel"><h3>{t('selected')} vs {t('reference')}</h3>{(['speed','throttle','brake','steering','delta'] as const).map(key=><TelemetryChart key={key} data={chart} field={key} reference={'ref'+key[0].toUpperCase()+key.slice(1)} title={t(key)} insights={report.insights.filter(i=>i.channel===key)}/>)}</section>}
 <section className="panel"><h3>{t('improve')}</h3><div className="recommendations">{report.improvement_actions.length?report.improvement_actions.map((r,i)=><article key={r.segment_id}><em>0{i+1}</em><div><h4>{segmentName(report.segments.find(s=>s.id===r.segment_id)?.name||r.segment_id)} · {t(r.title_key)}</h4><p>{t(r.message_key)}</p><small>{t('loss')}: {r.expected_gain.toFixed(3)}s</small></div></article>):<p className="muted">{t(report.data_sufficiency.message_key)}</p>}</div></section></>}</main></div></div>
}

function Metric({label,value,accent=false}:{label:string,value:string,accent?:boolean}){return <div className={accent?'metric accent':'metric'}><span>{label}</span><strong>{value}</strong></div>}
function InsightPanel({title,insights,empty}:{title:string;insights:Insight[];empty:string}){const{t}=useTranslation();return <section className="panel"><h3>{title}</h3><div className="insightGrid">{insights.length?insights.map(item=><article key={item.id} className={item.kind}><span className="insightIcon">✓</span><div><b>{t(item.title_key)}</b><p>{t(item.message_key)}</p><small>{t(item.status)} · {Math.abs(item.time_delta).toFixed(3)}s</small></div></article>):<p className="muted">{empty}</p>}</div></section>}

type ChartRow={x:number;speed:number;refSpeed:number;throttle:number;refThrottle:number;brake:number;refBrake:number;steering:number;refSteering:number;delta:number;refDelta:number}
function TelemetryChart({data,field,reference,title,insights}:{data:ChartRow[];field:keyof ChartRow;reference:string;title:string;insights:Insight[]}){return <div className="chart"><span>{title}</span><ResponsiveContainer width="100%" height={115}><LineChart data={data}><XAxis dataKey="x" hide/><YAxis width={42} tick={{fontSize:10}} domain={['auto','auto']}/><Tooltip labelFormatter={v=>`${Number(v).toFixed(1)}%`}/><Line dataKey={reference} stroke="#627087" dot={false} strokeWidth={1}/><Line dataKey={field} stroke="#e8ff47" dot={false} strokeWidth={2}/>{insights.map(i=>{const row=data[Math.min(data.length-1,Math.round(i.distance_pct*(data.length-1)))];return <ReferenceDot key={i.id} x={i.distance_pct*100} y={Number(row[field])} r={7} fill="#e8ff47" stroke="#090c11" label={{value:i.kind==='positive'?'✓':'!',fill:'#090c11',fontSize:9}}/>})}</LineChart></ResponsiveContainer></div>}

function TrackMapView({map}:{map:TrackMapType}){if(!map.available||!map.centerline.length)return null;const all=[...map.centerline,...map.best];const xs=all.map(p=>p.x),ys=all.map(p=>p.y);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=Math.max(maxX-minX,maxY-minY)*.08||1;const points=(items:{x:number;y:number}[])=>items.map(p=>`${p.x},${-p.y}`).join(' ');return <svg className="trackMap" viewBox={`${minX-pad} ${-maxY-pad} ${maxX-minX+2*pad} ${maxY-minY+2*pad}`} role="img"><polyline points={points(map.centerline)} className="mapOutline"/><polyline points={points(map.median)} className="mapMedian"/><polyline points={points(map.best)} className="mapBest"/>{map.corners.map((m,i)=><g key={`${m.label}-${i}`}><circle cx={m.x} cy={-m.y} r={5} className="cornerDot"/><text x={m.x+7} y={-m.y-7}>{i+1}</text><title>{m.label}</title></g>)}{map.insights.map(m=><g key={m.insight_id}><circle cx={m.x} cy={-m.y} r={9} className="mapInsight"/><text x={m.x} y={-m.y+3} textAnchor="middle" className="mapInsightText">{m.label}</text></g>)}</svg>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
